trainer_params:
  max_epochs: 2
  learning_rate: 0.00002
  batch_size: 2

model_params:
  model_root_dir: "~/.phoner_covid19/models/hf"
  model_n_version: "bert-crf"
  model_pretrain_path: "vinai/phobert-base"
  cache_dir: "~/.phoner_covid19/models/hf"
